/**
 * Curated morphemes for fictional organization and person names. Company names are
 * assembled from a head and a tail and rejected when they match a real company.
 */

export const COMPANY_HEADS: readonly string[] = [
  "Halcyon",
  "Kestrel",
  "Meridian",
  "Corvid",
  "Lumen",
  "Tessellate",
  "Northlight",
  "Vireo",
  "Alder",
  "Quill",
  "Aurelian",
  "Basalt",
  "Brightwater",
  "Cinder",
  "Cobalt",
  "Dunmore",
  "Ember",
  "Fathom",
  "Fennel",
  "Gale",
  "Garnet",
  "Glassbrook",
  "Harrow",
  "Heron",
  "Hollis",
  "Ironwood",
  "Kelvin",
  "Larkspur",
  "Linden",
  "Lodestar",
  "Marlow",
  "Mistral",
  "Nettle",
  "Oriel",
  "Osprey",
  "Pell",
  "Pinewood",
  "Quarry",
  "Ravel",
  "Rowan",
  "Sable",
  "Saffron",
  "Selkie",
  "Solace",
  "Sorrel",
  "Eventide",
  "Tamarind",
  "Thistle",
  "Tidewater",
  "Umber",
  "Vale",
  "Verdant",
  "Wren",
  "Yarrow",
  "Zephyr",
  "Argent",
  "Bramble",
  "Calloway",
  "Foxglove",
  "Greywater",
  "Hawthorn",
  "Kite",
  "Lantern",
  "Nimbus",
  "Oakridge",
  "Parallax",
  "Sparrow",
  "Tallow",
  "Vellum",
  "Willow",
  "Anvil",
  "Cairn",
  "Driftwood",
  "Granite",
  "Jasper",
  "Loam",
  "Nectar",
  "Orchard",
  "Pebble",
  "Reef",
  "Slate",
  "Vesper",
  "Birch",
  "Coral",
  "Fern",
  "Glacier",
  "Harbour",
  "Ochre",
  "Quartz",
  "Ridge",
  "Tundra",
  "Bellwether",
  "Skerry",
  "Elmwood",
  "Fjord",
  "Gyre",
  "Isthmus",
  "Knoll",
  "Lyrebird",
  "Lyric",
  "Moraine",
  "Nocturne",
  "Obsidian",
  "Palisade",
  "Riverstone",
  "Sundial",
  "Tarn",
  "Veridian",
  "Wildrose",
  "Brook",
  "Copperleaf",
  "Dawnfield",
  "Estuary",
  "Firth",
  "Gossamer",
  "Hearth",
  "Inlet",
  "Kelp",
  "Lacewing",
  "Marigold",
  "Nightjar",
  "Oleander",
  "Petrel",
];

export const COMPANY_TAILS: readonly string[] = [
  "Neural",
  "Neurotech",
  "Bioelectronics",
  "Interfaces",
  "Neurodynamics",
  "Labs",
  "Medical",
  "Therapeutics",
  "Neuro",
  "Neurosciences",
  "Neuroprosthetics",
  "Neuromodulation",
  "Biosciences",
  "Neuroengineering",
  "Systems",
  "Devices",
  "Biomedical",
  "Neuronics",
  "Bionics",
  "Neurotherapeutics",
  "Health",
  "Implants",
  "Neurostim",
  "Cortical",
];

/** Short forms of tails, used when a head alone would not be a unique short name. */
export const TAIL_ABBREVIATIONS: Record<string, string> = {
  Neural: "NL",
  Neurotech: "NT",
  Bioelectronics: "BE",
  Interfaces: "IF",
  Neurodynamics: "ND",
  Labs: "Labs",
  Medical: "Med",
  Therapeutics: "Tx",
  Neuro: "Nx",
  Neurosciences: "NS",
  Neuroprosthetics: "NP",
  Neuromodulation: "NM",
  Biosciences: "Bio",
  Neuroengineering: "NE",
  Systems: "Sys",
  Devices: "Dev",
  Biomedical: "BM",
  Neuronics: "Nn",
  Bionics: "Bx",
  Neurotherapeutics: "NTx",
  Health: "Hlth",
  Implants: "Imp",
  Neurostim: "NSt",
  Cortical: "Ctx",
};

/**
 * Real neurotechnology companies. Generated names are compared after normalisation
 * (lower case, punctuation removed) and any name containing "neuralink" is rejected.
 */
export const REAL_COMPANY_DENYLIST: readonly string[] = [
  "Neuralink",
  "Synchron",
  "Paradromics",
  "Blackrock Neurotech",
  "Precision Neuroscience",
  "Kernel",
  "NeuroPace",
  "Medtronic",
  "Boston Scientific",
  "Abbott",
  "Nevro",
  "INBRAIN",
  "CorTec",
  "Cognixion",
  "Axoft",
  "Science Corp",
  "Motif Neurotech",
  "Onward Medical",
  "Bios Health",
  "Neurable",
  "Emotiv",
  "Flow Neuroscience",
  "Cala Health",
  "SetPoint Medical",
  "electroCore",
  "LivaNova",
  "Second Sight",
  "Pixium Vision",
  "Bionic Vision",
  "Cochlear",
  "MED-EL",
  "Advanced Bionics",
  "Openwater",
  "Nudge",
  "Forest Neurotech",
  "Merge Labs",
  "Neurosity",
  "Brainco",
  "Wisp",
  "Ceribell",
  "Neurolutions",
  "Bioinduction",
  "Rune Labs",
  "Iota Biosciences",
  "Neuspera",
  "Salvia Bioelectronics",
  "Vivistim",
  "MicroTransponder",
  "Stentrode",
  "Utah Array",
  "Neuropixels",
  "OpenBCI",
  "Muse",
  "Kernel Flow",
];

export const INVESTOR_HEADS: readonly string[] = [
  "Kestrel Ridge",
  "Farrow Hill",
  "Meadowvale",
  "Corran Point",
  "Brightwater Bay",
  "Ashdown Park",
  "Highfield Row",
  "Larch Hollow",
  "Silvermere",
  "Thornbury Lane",
  "Westmarch",
  "Greyfell",
  "Marram Coast",
  "Ellery Cross",
  "Pinehurst Gate",
  "Redgrave",
  "Amberly",
  "Copperfield Row",
  "Duskmere",
  "Fenwick Bridge",
  "Glenmoor",
  "Harlow Reach",
  "Iverston",
  "Kingsfold",
  "Lowther Fell",
  "Morrow Street",
  "Northcote",
  "Oxbow",
  "Penrose Quay",
  "Quarry Lane",
  "Rathlin",
  "Saltmarsh",
  "Tenby Row",
  "Underhill",
  "Valemont",
];

export const INVESTOR_TAILS: readonly string[] = [
  "Capital",
  "Ventures",
  "Partners",
  "Health Ventures",
  "Growth Partners",
  "Bio Fund",
  "Innovation Fund",
  "Translational Fund",
];

export const UNIVERSITY_BASES: readonly string[] = [
  "Thornfield",
  "Calder",
  "Ashcombe",
  "Elderbrook",
  "Wexcastle",
  "Marrowick",
  "Brackenholm",
  "Cravenmoor",
  "Dovewell",
  "Fallowmere",
  "Glenarvon",
  "Hollowbrook",
  "Ivorley",
  "Jarrowgate",
  "Kestwick",
  "Lindenmoor",
  "Morrowfield",
  "Nethercote",
  "Oakhaven",
  "Pembrook",
  "Quillford",
  "Ravenshaw",
  "Tollbridge",
  "Umberly",
  "Wintermere",
  "Yarrowdale",
  "Zellwood",
  "Beckridge",
  "Dunmorrow",
  "Eastvale",
  "Fairhollow",
  "Greystone",
  "Highmoor",
  "Kingsmere",
  "Longwater",
  "Ambervale",
  "Coldharbour",
  "Ferncliffe",
  "Hazelmount",
  "Larkhill",
  "Mossgrove",
  "Northreach",
  "Ottersby",
  "Redmarsh",
  "Stonecross",
  "Thistlewood",
  "Wardlow",
  "Ashgrove",
  "Bramblewick",
];

export const UNIVERSITY_FORMATS: readonly string[] = [
  "{base} University",
  "University of {base}",
  "{base} Institute of Technology",
  "{base} Medical University",
  "{base} Polytechnic University",
];

export const HOSPITAL_BASES: readonly string[] = [
  "Ravenmoor",
  "Aldermere",
  "Corwen",
  "Lockhart",
  "Marisol",
  "Northgate",
  "Pellworth",
  "Sandmere",
  "Thackeray",
  "Varley",
  "Westerly",
  "Yardley",
  "Brindlewood",
  "Cotterill",
  "Ellingham",
  "Fairweather",
  "Gilmour",
  "Hartwell",
  "Ingleby",
  "Kingsley",
];

export const HOSPITAL_FORMATS: readonly string[] = [
  "{base} General Hospital",
  "{base} Memorial Hospital",
  "{base} University Hospital",
  "{base} Neurological Institute",
  "{base} Medical Center",
];

export const LAB_TOPICS: readonly string[] = [
  "Cortical Prosthetics",
  "Neural Decoding",
  "Bioelectronic Medicine",
  "Neural Interfaces",
  "Speech Neuroscience",
  "Sensory Restoration",
  "Motor Neuroprosthetics",
  "Closed-Loop Neuromodulation",
  "Neurophotonics",
  "Neural Signal Processing",
  "Spinal Circuits",
  "Auditory Prosthetics",
  "Retinal Engineering",
  "Neuroimaging Methods",
  "Vagal Physiology",
  "Peripheral Nerve Engineering",
  "Ultrasound Neuromodulation",
  "Epilepsy Systems",
  "Brain Stimulation Physics",
  "Neuroelectronic Materials",
  "Computational Neuroprosthetics",
  "Cognitive Neuroengineering",
  "Implantable Electronics",
  "Optogenetic Tools",
  "Translational Neurotechnology",
  "Neural Circuit Dynamics",
  "Wearable Neurophysiology",
  "Deep Brain Stimulation Research",
  "Neuromorphic Decoding",
  "Brain-Machine Interaction",
];

export const GOVERNMENT_AGENCY_NAMES: readonly string[] = [
  "National Neurotechnology Assessment Office",
  "Sample Federal Health Products Authority",
  "Regional Neuroscience Funding Council",
  "Sample Research Council for Bioengineering",
  "Institute for Sample Health Research Grants",
  "Office of Medical Device Evaluation (Sample)",
  "Sample National Rehabilitation Programme",
  "Ministry of Science Neurotechnology Directorate (Sample)",
];

export const NONPROFIT_NAMES: readonly string[] = [
  "Spinal Cord Recovery Foundation (Sample)",
  "Neural Interface Commons Alliance",
  "Hearing Restoration Trust (Sample)",
  "Sample Epilepsy Research Foundation",
  "Vision Restoration Fund (Sample)",
  "Neurotechnology Ethics Collaborative",
  "Paralysis Innovation Charity (Sample)",
  "Sample Movement Disorders Society",
];

export const FIRST_NAMES: readonly string[] = [
  "Amara",
  "Anika",
  "Bao",
  "Carlos",
  "Chiara",
  "Daniel",
  "Dmitri",
  "Elena",
  "Emeka",
  "Farah",
  "Fatima",
  "Gabriel",
  "Hana",
  "Hiroshi",
  "Ines",
  "Isabel",
  "Jonas",
  "Kwame",
  "Laila",
  "Leon",
  "Lucia",
  "Mateo",
  "Mei",
  "Nadia",
  "Nikolai",
  "Noor",
  "Olivia",
  "Omar",
  "Priya",
  "Rafael",
  "Rania",
  "Ravi",
  "Rosa",
  "Samuel",
  "Sofia",
  "Tariq",
  "Thea",
  "Tomas",
  "Valentina",
  "Wei",
  "Yara",
  "Yusuf",
  "Zanele",
  "Aiden",
  "Beatriz",
  "Caleb",
  "Dara",
  "Elif",
  "Femi",
  "Greta",
  "Hugo",
  "Ingrid",
  "Jae",
  "Kenji",
  "Lior",
  "Maren",
  "Naomi",
  "Oskar",
  "Petra",
  "Quentin",
  "Rhea",
  "Soren",
  "Tamsin",
  "Uma",
  "Viktor",
  "Ximena",
  "Yuki",
  "Zoe",
  "Arjun",
  "Bianca",
  "Cyrus",
  "Esme",
  "Finn",
  "Gwen",
  "Harun",
  "Ida",
  "Jamal",
  "Kira",
  "Lena",
  "Malik",
];

export const LAST_NAMES: readonly string[] = [
  "Okafor",
  "Nakamura",
  "Fernandes",
  "Lindqvist",
  "Haddad",
  "Petrov",
  "Mbeki",
  "Rossi",
  "Schneider",
  "Tanaka",
  "Almeida",
  "Kowalski",
  "Byrne",
  "Chaudhary",
  "Delacroix",
  "Eriksen",
  "Farouk",
  "Goldberg",
  "Huang",
  "Ivanova",
  "Jansen",
  "Kaur",
  "Laurent",
  "Moreau",
  "Nyström",
  "Oyelaran",
  "Park",
  "Quinn",
  "Rahman",
  "Sato",
  "Torres",
  "Ueda",
  "Varga",
  "Wallace",
  "Xu",
  "Yilmaz",
  "Zhang",
  "Abernathy",
  "Bergström",
  "Castellanos",
  "Dimitriou",
  "Ekwueme",
  "Fischer",
  "Gallagher",
  "Hernández",
  "Iqbal",
  "Jokinen",
  "Kimura",
  "Lombardi",
  "Mensah",
  "Novak",
  "Osei",
  "Popescu",
  "Reyes",
  "Sørensen",
  "Takahashi",
  "Villanueva",
  "Whitaker",
  "Yamamoto",
  "Zielinski",
  "Andersson",
  "Brennan",
  "Costa",
  "Dubois",
  "Ellison",
  "Fujita",
  "Grant",
  "Holm",
  "Ito",
  "Jensen",
  "Adeyemi",
  "Blackwood",
  "Carvalho",
  "Draganov",
  "Esposito",
  "Ferreira",
  "Gupta",
  "Hossain",
  "Ibrahim",
  "Kaplan",
];

export const NEWS_OUTLETS: readonly string[] = [
  "Sample Neurotech Wire",
  "The Cortex Ledger",
  "Interface Weekly",
  "Neuromodulation Report (Sample)",
  "Sample Health Technology Review",
  "Brainwave Bulletin",
  "Implant Insider (Sample)",
  "Signal and Spike",
  "Sample Clinical Devices Daily",
  "The Neuroprosthetics Observer",
];

export const JOURNALS: readonly string[] = [
  "Journal of Sample Neuroengineering",
  "Sample Neural Interfaces Letters",
  "Annals of Neuroprosthetic Medicine (Sample)",
  "Sample Journal of Neuromodulation",
  "Clinical Neurotechnology Reports (Sample)",
  "Sample Transactions on Biomedical Circuits",
  "Frontiers of Sample Neuroscience",
  "Sample Journal of Rehabilitation Engineering",
  "Sensory Prosthetics Quarterly (Sample)",
];

export const CONFERENCES: readonly string[] = [
  "Sample International Neural Engineering Conference",
  "Sample Neurotechnology Symposium",
  "Sample Brain-Computer Interface Meeting",
];

export const PREPRINT_SERVER = "Sample Neuroscience Preprints";
export const REGISTRY_NAME = "sample-registry";
export const REGISTRY_PUBLISHER = "Sample Clinical Trial Registry";
export const PATENT_OFFICE = "Sample Patent Register";
