import { defineArchetype } from "./types";

export const BCI_ARCHETYPES = [
  defineArchetype({
    key: "speech_intracortical",
    label: "implanted speech neuroprosthesis",
    productPhrase:
      "implanted speech neuroprostheses that decode attempted speech from motor cortex for speech restoration",
    interfaceType: "intracortical",
    invasiveness: "invasive",
    modality: "recording",
    categories: ["implantable-bcis", "brain-computer-interfaces", "neural-decoding-software"],
    conditions: ["amyotrophic-lateral-sclerosis", "locked-in-syndrome", "brainstem-stroke"],
    neuralTargets: [
      "ventral precentral gyrus",
      "speech motor cortex",
      "dorsal laryngeal motor cortex",
    ],
    intendedFunctions: [
      "speech restoration through neural decoding of attempted speech",
      "text and synthesized-voice communication decoded from cortical activity",
    ],
    intendedUsers:
      "adults who have lost the ability to speak because of ALS, brainstem stroke or locked-in syndrome",
    deviceNouns: ["Speech Array", "Speech Interface", "Cortical Speech System", "Voice Array"],
    limitations: [
      "Requires a craniotomy and a percutaneous or wireless connection",
      "Decoder must be recalibrated as recorded signals drift",
      "Vocabulary size was limited in early studies",
      "Tested in a small number of participants",
    ],
    metrics: [
      {
        name: "decoded words per minute",
        unit: "words/min",
        low: 15,
        high: 80,
        higherIsBetter: true,
        decimals: 0,
      },
      { name: "word error rate", unit: "%", low: 8, high: 35, higherIsBetter: false, decimals: 1 },
    ],
    trialTitles: [
      "Neural Decoding of Attempted Speech With the {device} in Adults With {condition}",
      "Feasibility of Real-Time Neural Decoding for Speech Restoration Using the {device}",
      "Early Feasibility Study of the {device} Speech Neuroprosthesis in {condition}",
    ],
    primaryOutcomes: [
      "Word error rate of decoded sentences at 3 months",
      "Decoded words per minute during cued sentence tasks",
      "Device-related serious adverse events through 12 months",
    ],
    publicationTitles: [
      "Neural decoding of attempted speech from ventral precentral cortex in a participant with {condition}",
      "A speech neuroprosthesis using {channels}-channel intracortical recordings",
      "Stability of speech decoding from motor cortex over {months} months of home use",
      "Phoneme-level decoding of attempted speech with the {device}",
    ],
    patentTitles: [
      "Method for decoding attempted speech from intracortical neural signals",
      "Implantable electrode array for recording from speech motor cortex",
      "Language-model-assisted neural speech decoder",
    ],
    stageWeights: { research: 1, preclinical: 2, early_feasibility: 6, pivotal: 1 },
    decoding: true,
    keywords: [
      "speech neuroprosthesis",
      "speech restoration",
      "neural decoding",
      "intracortical array",
      "brain-computer interface",
    ],
    forcedCompanies: 5,
    forcedDevices: 5,
  }),
  defineArchetype({
    key: "speech_ecog",
    label: "ECoG speech neuroprosthesis",
    productPhrase:
      "electrocorticography-based speech neuroprostheses that decode attempted speech from the cortical surface for speech restoration",
    interfaceType: "ecog",
    invasiveness: "invasive",
    modality: "recording",
    categories: ["implantable-bcis", "brain-computer-interfaces", "neural-decoding-software"],
    conditions: [
      "locked-in-syndrome",
      "amyotrophic-lateral-sclerosis",
      "brainstem-stroke",
      "aphasia",
    ],
    neuralTargets: [
      "sensorimotor cortex surface (subdural ECoG grid)",
      "ventral sensorimotor cortex",
    ],
    intendedFunctions: [
      "speech restoration by decoding attempted speech from high-density ECoG",
      "decoding of attempted articulation into text and synthesized speech",
    ],
    intendedUsers: "adults with severe paralysis and anarthria",
    deviceNouns: ["Cortical Grid", "Speech Grid", "ECoG Speech System", "Surface Array"],
    limitations: [
      "Requires craniotomy for grid placement",
      "Signal quality depends on grid placement over speech cortex",
      "Decoding evaluated on constrained sentence sets",
    ],
    metrics: [
      {
        name: "decoded words per minute",
        unit: "words/min",
        low: 10,
        high: 70,
        higherIsBetter: true,
        decimals: 0,
      },
      { name: "word error rate", unit: "%", low: 10, high: 40, higherIsBetter: false, decimals: 1 },
    ],
    trialTitles: [
      "Neural Decoding of Attempted Speech From High-Density ECoG With the {device}",
      "Feasibility Study of Neural Decoding for Communication With the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Word error rate of decoded sentences at 6 months",
      "Rate of device-related adverse events through 12 months",
    ],
    publicationTitles: [
      "Decoding attempted speech from the cortical surface with a {channels}-electrode grid in {condition}",
      "Silent speech decoding from ventral sensorimotor cortex using the {device}",
      "Long-term ECoG signal stability over {months} months in a speech neuroprosthesis participant",
    ],
    patentTitles: [
      "High-density electrocorticography grid with integrated amplification",
      "System for decoding speech from cortical surface potentials",
    ],
    stageWeights: { research: 1, preclinical: 2, early_feasibility: 5, pivotal: 1 },
    decoding: true,
    keywords: [
      "electrocorticography",
      "ECoG",
      "speech restoration",
      "neural decoding",
      "speech neuroprosthesis",
    ],
    forcedCompanies: 4,
    forcedDevices: 4,
  }),
  defineArchetype({
    key: "motor_bci",
    label: "intracortical motor brain-computer interface",
    productPhrase:
      "intracortical brain-computer interfaces that decode intended movement for cursor, keyboard and robotic-arm control",
    interfaceType: "intracortical",
    invasiveness: "invasive",
    modality: "recording",
    categories: ["implantable-bcis", "brain-computer-interfaces", "neural-decoding-software"],
    conditions: [
      "tetraplegia",
      "spinal-cord-injury",
      "amyotrophic-lateral-sclerosis",
      "brainstem-stroke",
    ],
    neuralTargets: [
      "hand knob area of primary motor cortex",
      "dorsal premotor cortex",
      "primary motor cortex",
    ],
    intendedFunctions: [
      "neural decoding of intended movement for computer cursor and keyboard control",
      "control of robotic arms and functional electrical stimulation from decoded motor intent",
    ],
    intendedUsers: "adults with tetraplegia from spinal cord injury, ALS or brainstem stroke",
    deviceNouns: ["Motor Array", "Cortex Interface", "Motor Cortex System", "Intent Decoder"],
    limitations: [
      "Requires craniotomy and a transcutaneous or wireless link",
      "Performance declines as electrode signal quality changes over years",
      "Daily decoder calibration was needed in early studies",
    ],
    metrics: [
      {
        name: "cursor control bit rate",
        unit: "bits/s",
        low: 1,
        high: 4.5,
        higherIsBetter: true,
        decimals: 2,
      },
      {
        name: "target acquisition time",
        unit: "s",
        low: 0.8,
        high: 3,
        higherIsBetter: false,
        decimals: 2,
      },
    ],
    trialTitles: [
      "Neural Decoding of Intended Movement for Cursor Control With the {device} in People With {condition}",
      "Early Feasibility Study of Neural Decoding for Assistive Device Control Using the {device}",
      "Home Use of the {device} Intracortical Brain-Computer Interface in {condition}",
    ],
    primaryOutcomes: [
      "Typing rate in correct characters per minute at 6 months",
      "Cursor control bit rate during a standardised target task",
      "Serious adverse events through 12 months",
    ],
    publicationTitles: [
      "Neural decoding of intended hand movement for cursor control in a participant with {condition}",
      "Independent home use of an intracortical brain-computer interface over {months} months",
      "Decoding handwriting intent from {channels} intracortical channels",
      "Robotic arm control through an intracortical brain-computer interface in {condition}",
    ],
    patentTitles: [
      "Neural decoder with adaptive recalibration for cursor control",
      "Wireless intracortical recording implant with on-device spike sorting",
      "Method for decoding handwriting intent from motor cortex activity",
    ],
    stageWeights: { research: 1, preclinical: 2, early_feasibility: 5, pivotal: 2 },
    decoding: true,
    keywords: [
      "motor decoding",
      "intracortical array",
      "cursor control",
      "brain-computer interface",
      "tetraplegia",
    ],
    forcedCompanies: 6,
    forcedDevices: 6,
  }),
  defineArchetype({
    key: "endovascular_bci",
    label: "endovascular brain-computer interface",
    productPhrase:
      "endovascular brain-computer interfaces with stent-mounted electrodes delivered through the venous system",
    interfaceType: "endovascular",
    invasiveness: "minimally_invasive",
    modality: "recording",
    categories: ["endovascular-bcis", "brain-computer-interfaces", "neural-decoding-software"],
    conditions: ["amyotrophic-lateral-sclerosis", "spinal-cord-injury", "stroke", "tetraplegia"],
    neuralTargets: [
      "motor cortex via the superior sagittal sinus",
      "sensorimotor cortex adjacent to the sagittal sinus",
    ],
    intendedFunctions: [
      "neural decoding of motor intent for digital device control without open brain surgery",
      "switch-based communication decoded from endovascular recordings",
    ],
    intendedUsers: "adults with severe paralysis who are not candidates for craniotomy",
    deviceNouns: [
      "Venous Array",
      "Endovascular Array",
      "Sinus Electrode System",
      "Vascular Interface",
    ],
    limitations: [
      "Signal bandwidth is lower than intracortical recording",
      "Requires lifelong antiplatelet therapy in early protocols",
      "Limited number of independent control signals",
    ],
    metrics: [
      {
        name: "switch selection accuracy",
        unit: "%",
        low: 80,
        high: 98,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "selections per minute",
        unit: "per min",
        low: 4,
        high: 16,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Early Feasibility Study of Endovascular Neural Decoding With the {device} in Severe Paralysis",
      "Neural Decoding of Motor Intent Using the {device} Endovascular Interface in {condition}",
    ],
    primaryOutcomes: [
      "Incidence of device-related serious adverse events at 12 months",
      "Switch selection accuracy in a standardised task at 3 months",
    ],
    publicationTitles: [
      "Motor neuroprosthesis implanted through the jugular vein in participants with {condition}",
      "Endovascular recording of motor cortex for digital device control over {months} months",
      "Vascular patency after endovascular electrode array implantation",
    ],
    patentTitles: [
      "Stent-mounted electrode array for endovascular neural recording",
      "Method of delivering a neural interface through the venous system",
    ],
    stageWeights: { preclinical: 2, early_feasibility: 5, pivotal: 2 },
    decoding: true,
    keywords: [
      "endovascular",
      "stent electrode",
      "minimally invasive brain-computer interface",
      "neural decoding",
    ],
    forcedCompanies: 4,
    forcedDevices: 4,
  }),
  defineArchetype({
    key: "decoding_software",
    label: "neural decoding software platform",
    productPhrase:
      "neural decoding software that translates recorded neural signals into intended actions for brain-computer interfaces",
    interfaceType: "other",
    invasiveness: "noninvasive",
    modality: "recording",
    categories: ["neural-decoding-software", "closed-loop-systems", "brain-computer-interfaces"],
    conditions: ["tetraplegia", "amyotrophic-lateral-sclerosis", "spinal-cord-injury"],
    neuralTargets: ["motor and speech cortex recordings from partner devices"],
    intendedFunctions: [
      "neural decoding, calibration and signal-quality analytics for implanted and noninvasive recording systems",
    ],
    intendedUsers: "device developers and research groups running brain-computer interface studies",
    deviceNouns: ["Decoder Suite", "Signal Platform"],
    limitations: ["Performance depends on the recording hardware it is paired with"],
    metrics: [
      {
        name: "decoder calibration time",
        unit: "min",
        low: 2,
        high: 20,
        higherIsBetter: false,
        decimals: 0,
      },
    ],
    trialTitles: ["Evaluation of the {device} Neural Decoding Platform in {condition}"],
    primaryOutcomes: ["Decoding accuracy relative to a reference decoder"],
    publicationTitles: [
      "Self-recalibrating neural decoders for long-term brain-computer interface use",
      "Transfer learning across participants for intracortical neural decoding",
      "Benchmarking neural decoding algorithms on {channels}-channel recordings",
    ],
    patentTitles: [
      "Adaptive neural decoder with unsupervised recalibration",
      "Method for aligning neural population activity across recording sessions",
    ],
    stageWeights: { research: 3, preclinical: 1, early_feasibility: 2, commercial: 1 },
    decoding: true,
    producesDevices: false,
    keywords: ["neural decoding", "machine learning", "decoder calibration", "closed-loop"],
    forcedCompanies: 6,
    forcedDevices: 0,
  }),
  defineArchetype({
    key: "recording_hardware",
    label: "high-density neural recording probe",
    productPhrase:
      "high-density neural recording hardware, including silicon probes and flexible electrode arrays, for research and clinical recording",
    interfaceType: "intracortical",
    invasiveness: "invasive",
    modality: "recording",
    categories: ["neural-recording-hardware", "implantable-bcis"],
    conditions: ["epilepsy", "parkinson-disease"],
    neuralTargets: [
      "cortical layers 2 to 6",
      "hippocampus and cortex in research models",
      "intraoperative cortical recording sites",
    ],
    intendedFunctions: [
      "large-scale single-unit and local field potential recording",
      "flexible thin-film electrode arrays that reduce tissue response",
    ],
    intendedUsers: "neuroscience research laboratories and neurosurgical research programmes",
    deviceNouns: ["Probe", "Flex Array", "Recording System", "Thin-Film Array"],
    limitations: [
      "Research use only in most configurations",
      "Insertion requires a dedicated shuttle",
      "Chronic longevity in humans not yet established",
    ],
    metrics: [
      {
        name: "recording channels",
        unit: "channels",
        low: 256,
        high: 4096,
        higherIsBetter: true,
        decimals: 0,
      },
      {
        name: "single units per probe",
        unit: "units",
        low: 40,
        high: 400,
        higherIsBetter: true,
        decimals: 0,
      },
    ],
    trialTitles: [
      "Intraoperative Recording With the {device} During Neurosurgery for {condition}",
      "Safety of Short-Term Implantation of the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Number of single units recorded per probe",
      "Procedure-related adverse events at 30 days",
    ],
    publicationTitles: [
      "A {channels}-channel flexible neural probe with chronic recording stability over {months} months",
      "Tissue response to thin-film intracortical arrays in a rodent model",
      "Intraoperative single-unit recording with the {device} in patients with {condition}",
    ],
    patentTitles: [
      "Flexible thin-film neural probe with integrated multiplexing",
      "Insertion shuttle for flexible electrode arrays",
      "Polymer electrode array with reduced foreign-body response",
    ],
    stageWeights: { research: 4, preclinical: 3, early_feasibility: 2, commercial: 1 },
    keywords: [
      "neural probe",
      "single-unit recording",
      "flexible electrodes",
      "neural recording hardware",
    ],
    forcedCompanies: 4,
    forcedDevices: 3,
  }),
] as const;
