import { defineArchetype } from "./types";

export const NEUROMODULATION_ARCHETYPES = [
  defineArchetype({
    key: "dbs",
    label: "deep brain stimulation system",
    productPhrase:
      "deep brain stimulation systems with directional leads for movement and psychiatric disorders",
    interfaceType: "deep_brain_stimulation",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["deep-brain-stimulation", "neuromodulation"],
    conditions: [
      "parkinson-disease",
      "essential-tremor",
      "dystonia",
      "obsessive-compulsive-disorder",
    ],
    neuralTargets: [
      "subthalamic nucleus",
      "globus pallidus internus",
      "ventral intermediate nucleus of the thalamus",
    ],
    intendedFunctions: [
      "deep brain stimulation for motor symptom control",
      "directional stimulation with a reduced side-effect window",
    ],
    intendedUsers:
      "adults with advanced movement disorders that no longer respond adequately to medication",
    deviceNouns: ["DBS System", "Directional Lead", "Pulse Generator", "Deep Brain Platform"],
    limitations: [
      "Requires stereotactic neurosurgery",
      "Battery replacement or recharging is required",
      "Programming visits are needed to optimise stimulation",
    ],
    metrics: [
      {
        name: "motor score improvement",
        unit: "%",
        low: 30,
        high: 65,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "battery longevity",
        unit: "years",
        low: 3,
        high: 15,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Directional Deep Brain Stimulation With the {device} for {condition}",
      "Randomized Study of the {device} Deep Brain Stimulation System in {condition}",
      "Long-Term Follow-Up of Deep Brain Stimulation With the {device}",
    ],
    primaryOutcomes: [
      "Change in motor score at 12 months",
      "Stimulation-induced side effects during monopolar review",
      "Device-related adverse events at 24 months",
    ],
    publicationTitles: [
      "Directional deep brain stimulation of the subthalamic nucleus in {n} patients with {condition}",
      "Five-year outcomes of deep brain stimulation with the {device}",
      "Local field potentials recorded from DBS leads predict motor fluctuations in {condition}",
    ],
    patentTitles: [
      "Directional deep brain stimulation lead with segmented contacts",
      "Rechargeable implantable pulse generator with sensing",
      "Method for steering current in a segmented DBS lead",
    ],
    stageWeights: {
      preclinical: 1,
      early_feasibility: 2,
      pivotal: 2,
      regulatory_review: 1,
      authorized: 2,
      commercial: 3,
    },
    keywords: [
      "deep brain stimulation",
      "DBS",
      "directional lead",
      "movement disorders",
      "neuromodulation",
    ],
    forcedCompanies: 5,
    forcedDevices: 4,
  }),
  defineArchetype({
    key: "adaptive_dbs",
    label: "adaptive deep brain stimulation system",
    productPhrase:
      "closed-loop deep brain stimulation systems that record local field potentials and adjust stimulation in real time",
    interfaceType: "deep_brain_stimulation",
    invasiveness: "invasive",
    modality: "both",
    categories: [
      "deep-brain-stimulation",
      "closed-loop-systems",
      "neuromodulation",
      "responsive-neurostimulation",
    ],
    conditions: ["parkinson-disease", "essential-tremor", "major-depressive-disorder", "epilepsy"],
    neuralTargets: [
      "subthalamic nucleus with beta-band sensing",
      "anterior nucleus of the thalamus",
      "subcallosal cingulate",
    ],
    intendedFunctions: [
      "adaptive deep brain stimulation driven by recorded biomarkers",
      "closed-loop stimulation that responds to beta-band local field potentials",
    ],
    intendedUsers:
      "adults with Parkinson disease, tremor or treatment-resistant psychiatric illness who are candidates for DBS",
    deviceNouns: [
      "Adaptive DBS",
      "Sense-and-Stim System",
      "Closed-Loop Stimulator",
      "Neural Sensing Platform",
    ],
    limitations: [
      "Biomarker availability varies between patients",
      "Sensing is disrupted by stimulation artefact",
      "Long-term benefit over conventional DBS not yet established",
    ],
    metrics: [
      {
        name: "time with troublesome dyskinesia",
        unit: "%",
        low: 5,
        high: 30,
        higherIsBetter: false,
        decimals: 1,
      },
      {
        name: "energy delivered relative to continuous stimulation",
        unit: "%",
        low: 40,
        high: 90,
        higherIsBetter: false,
        decimals: 0,
      },
    ],
    trialTitles: [
      "Adaptive Deep Brain Stimulation With the {device} for {condition}: A Randomized Crossover Study",
      "Closed-Loop Stimulation Using Local Field Potential Biomarkers With the {device}",
    ],
    primaryOutcomes: [
      "Time with good on-state without dyskinesia at 3 months",
      "Motor fluctuations measured by diary at 6 months",
    ],
    publicationTitles: [
      "Adaptive deep brain stimulation guided by beta-band activity in {n} patients with {condition}",
      "Chronic local field potential recording with the {device} over {months} months",
      "Closed-loop stimulation of the subcallosal cingulate for treatment-resistant depression",
    ],
    patentTitles: [
      "Closed-loop neurostimulator with artefact-rejecting sensing",
      "Method for adapting stimulation amplitude to a neural biomarker",
    ],
    stageWeights: { research: 1, preclinical: 1, early_feasibility: 3, pivotal: 2, authorized: 1 },
    keywords: [
      "adaptive DBS",
      "closed-loop",
      "local field potentials",
      "deep brain stimulation",
      "biomarker",
    ],
    forcedCompanies: 3,
    forcedDevices: 3,
  }),
  defineArchetype({
    key: "scs",
    label: "spinal cord stimulation system",
    productPhrase:
      "spinal cord stimulation systems for chronic pain, including high-frequency and burst paradigms",
    interfaceType: "spinal_cord_stimulation",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["spinal-cord-stimulation", "neuromodulation"],
    conditions: ["chronic-pain", "phantom-limb-pain"],
    neuralTargets: ["dorsal columns of the thoracic spinal cord", "dorsal root ganglion"],
    intendedFunctions: [
      "spinal cord stimulation for chronic neuropathic pain of the trunk and limbs",
      "paresthesia-free high-frequency stimulation",
    ],
    intendedUsers:
      "adults with chronic neuropathic pain that has not responded to conservative treatment",
    deviceNouns: [
      "Spinal Stimulator",
      "Dorsal Column System",
      "Pain Stimulator",
      "Epidural Lead System",
    ],
    limitations: [
      "Lead migration can reduce effect",
      "Requires a trial period before permanent implantation",
      "Placebo response complicates effect estimates",
    ],
    metrics: [
      {
        name: "pain score reduction",
        unit: "%",
        low: 35,
        high: 70,
        higherIsBetter: true,
        decimals: 1,
      },
      { name: "responder rate", unit: "%", low: 45, high: 85, higherIsBetter: true, decimals: 1 },
    ],
    trialTitles: [
      "Randomized Study of the {device} Spinal Cord Stimulation System for {condition}",
      "Post-Market Study of the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Proportion of participants with at least 50% pain reduction at 3 months",
      "Change in pain score at 12 months",
    ],
    publicationTitles: [
      "High-frequency spinal cord stimulation with the {device} in {n} patients with {condition}",
      "Twelve-month outcomes of burst spinal cord stimulation for {condition}",
      "Dorsal root ganglion stimulation for focal neuropathic pain: a prospective series",
    ],
    patentTitles: [
      "Paddle lead for high-frequency spinal cord stimulation",
      "Method for paresthesia-free spinal cord stimulation",
      "Anchoring system for epidural leads",
    ],
    stageWeights: {
      early_feasibility: 1,
      pivotal: 2,
      regulatory_review: 1,
      authorized: 2,
      commercial: 3,
    },
    keywords: [
      "spinal cord stimulation",
      "chronic pain",
      "epidural stimulation",
      "neuromodulation",
    ],
    forcedCompanies: 4,
    forcedDevices: 3,
  }),
  defineArchetype({
    key: "scs_sci",
    label: "epidural spinal cord stimulation for paralysis",
    productPhrase:
      "targeted epidural spinal cord stimulation systems that restore standing and stepping after spinal cord injury",
    interfaceType: "spinal_cord_stimulation",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["spinal-cord-stimulation", "neurorehabilitation", "neuromodulation"],
    conditions: ["spinal-cord-injury", "tetraplegia"],
    neuralTargets: ["lumbosacral dorsal roots", "cervical dorsal roots"],
    intendedFunctions: [
      "epidural electrical stimulation to restore voluntary leg movement after spinal cord injury",
      "stimulation-assisted arm and hand function in cervical injury",
    ],
    intendedUsers: "adults with chronic incomplete or complete spinal cord injury",
    deviceNouns: ["Spinal Recovery System", "Epidural Array", "Locomotion Stimulator"],
    limitations: [
      "Benefit requires intensive rehabilitation alongside stimulation",
      "Studied in small cohorts",
      "Effect size varies with injury level",
    ],
    metrics: [
      {
        name: "walking distance in six minutes",
        unit: "m",
        low: 20,
        high: 200,
        higherIsBetter: true,
        decimals: 0,
      },
      {
        name: "upper-limb motor score change",
        unit: "points",
        low: 3,
        high: 12,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Targeted Epidural Stimulation With the {device} to Restore Walking After {condition}",
      "Cervical Epidural Stimulation With the {device} for Hand Function in {condition}",
    ],
    primaryOutcomes: ["Six-minute walk distance at 6 months", "Upper-limb motor score at 3 months"],
    publicationTitles: [
      "Epidural stimulation restores stepping in {n} participants with chronic {condition}",
      "Activity-dependent recovery with the {device} over {months} months",
      "Spatiotemporal stimulation of lumbosacral roots for locomotion after {condition}",
    ],
    patentTitles: [
      "Spatiotemporal epidural stimulation controller for locomotion",
      "Paddle electrode array shaped to lumbosacral dorsal roots",
    ],
    stageWeights: { preclinical: 1, early_feasibility: 4, pivotal: 2 },
    keywords: [
      "epidural stimulation",
      "spinal cord injury",
      "locomotion",
      "neurorehabilitation",
      "spinal cord stimulation",
    ],
    forcedCompanies: 2,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "pns",
    label: "peripheral nerve stimulation system",
    productPhrase:
      "peripheral nerve stimulation systems, including percutaneous and injectable stimulators for pain and neurological disorders",
    interfaceType: "peripheral_nerve",
    invasiveness: "minimally_invasive",
    modality: "stimulation",
    categories: ["peripheral-nerve-stimulation", "neuromodulation"],
    conditions: [
      "chronic-pain",
      "migraine",
      "overactive-bladder",
      "phantom-limb-pain",
      "cluster-headache",
    ],
    neuralTargets: [
      "occipital nerve",
      "tibial nerve",
      "median nerve",
      "sciatic nerve",
      "sphenopalatine ganglion",
    ],
    intendedFunctions: [
      "peripheral nerve stimulation for chronic pain",
      "percutaneous nerve stimulation delivered through a wearable pulse generator",
    ],
    intendedUsers: "adults with focal chronic pain, migraine or bladder dysfunction",
    deviceNouns: [
      "Nerve Stimulator",
      "Peripheral Stimulator",
      "Micro Stimulator",
      "Nerve Cuff System",
    ],
    limitations: [
      "Lead placement requires ultrasound guidance",
      "Durability of pain relief after removal is uncertain",
      "Wearable components must be worn during treatment",
    ],
    metrics: [
      {
        name: "pain score reduction",
        unit: "%",
        low: 30,
        high: 65,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "monthly migraine days reduction",
        unit: "days",
        low: 2,
        high: 7,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Percutaneous Peripheral Nerve Stimulation With the {device} for {condition}",
      "Randomized Sham-Controlled Study of the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Change in average pain score at 3 months",
      "Reduction in monthly migraine days at 12 weeks",
    ],
    publicationTitles: [
      "Peripheral nerve stimulation with an injectable microstimulator in {n} patients with {condition}",
      "Sixty-day percutaneous peripheral nerve stimulation for {condition}: a prospective study",
      "Occipital nerve stimulation for {condition} with the {device}",
    ],
    patentTitles: [
      "Injectable peripheral nerve stimulator with wireless power",
      "Nerve cuff electrode with self-sizing geometry",
      "Wearable transmitter for percutaneous nerve stimulation",
    ],
    stageWeights: {
      preclinical: 1,
      early_feasibility: 2,
      pivotal: 2,
      regulatory_review: 1,
      authorized: 2,
      commercial: 2,
    },
    keywords: [
      "peripheral nerve stimulation",
      "PNS",
      "nerve cuff",
      "percutaneous stimulation",
      "neuromodulation",
    ],
    forcedCompanies: 8,
    forcedDevices: 4,
  }),
  defineArchetype({
    key: "hypoglossal",
    label: "hypoglossal nerve stimulation system",
    productPhrase: "hypoglossal nerve stimulation systems for obstructive sleep apnea",
    interfaceType: "peripheral_nerve",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["peripheral-nerve-stimulation", "neuromodulation"],
    conditions: ["obstructive-sleep-apnea"],
    neuralTargets: ["hypoglossal nerve", "protrusor branches of the hypoglossal nerve"],
    intendedFunctions: [
      "respiration-synchronised hypoglossal nerve stimulation to keep the airway open during sleep",
    ],
    intendedUsers:
      "adults with moderate-to-severe obstructive sleep apnea who cannot tolerate positive airway pressure",
    deviceNouns: ["Airway Stimulator", "Sleep Stimulator", "Hypoglossal System"],
    limitations: [
      "Requires surgical implantation with respiratory sensing",
      "Not suitable for complete concentric collapse",
      "Nightly patient activation required",
    ],
    metrics: [
      {
        name: "apnea-hypopnea index reduction",
        unit: "%",
        low: 50,
        high: 80,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Hypoglossal Nerve Stimulation With the {device} for {condition}",
      "Post-Approval Registry of the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Reduction in apnea-hypopnea index at 12 months",
      "Oxygen desaturation index at 6 months",
    ],
    publicationTitles: [
      "Hypoglossal nerve stimulation with the {device} in {n} patients with {condition}",
      "Two-year outcomes of respiration-synchronised hypoglossal stimulation",
    ],
    patentTitles: [
      "Respiration-synchronised hypoglossal nerve stimulator",
      "Bilateral hypoglossal cuff electrode",
    ],
    stageWeights: { pivotal: 2, regulatory_review: 1, authorized: 2, commercial: 2 },
    keywords: [
      "hypoglossal nerve stimulation",
      "sleep apnea",
      "peripheral nerve stimulation",
      "airway",
    ],
    forcedCompanies: 2,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "sacral",
    label: "sacral neuromodulation system",
    productPhrase: "sacral neuromodulation systems for bladder and bowel control",
    interfaceType: "peripheral_nerve",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["peripheral-nerve-stimulation", "neuromodulation"],
    conditions: ["overactive-bladder", "chronic-pain"],
    neuralTargets: ["S3 sacral nerve root"],
    intendedFunctions: [
      "sacral nerve stimulation for refractory overactive bladder and urinary retention",
    ],
    intendedUsers:
      "adults with overactive bladder or non-obstructive urinary retention refractory to medication",
    deviceNouns: ["Sacral Stimulator", "Bladder Control System", "Sacral Lead System"],
    limitations: [
      "Requires a staged trial before implantation",
      "Lead revision is needed in a minority of patients",
    ],
    metrics: [
      {
        name: "urgency incontinence episodes reduction",
        unit: "%",
        low: 50,
        high: 85,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Sacral Neuromodulation With the {device} for {condition}",
      "Rechargeable Sacral Neuromodulation Using the {device}",
    ],
    primaryOutcomes: [
      "Proportion of responders with 50% reduction in incontinence episodes at 6 months",
    ],
    publicationTitles: [
      "Rechargeable sacral neuromodulation with the {device} in {n} patients with {condition}",
      "Long-term efficacy of sacral neuromodulation over {months} months",
    ],
    patentTitles: [
      "Miniaturised rechargeable sacral neurostimulator",
      "Tined lead for sacral nerve stimulation",
    ],
    stageWeights: { pivotal: 1, authorized: 2, commercial: 3 },
    keywords: ["sacral neuromodulation", "overactive bladder", "peripheral nerve stimulation"],
    forcedCompanies: 2,
    forcedDevices: 1,
  }),
  defineArchetype({
    key: "vns",
    label: "implanted vagus nerve stimulation system",
    productPhrase:
      "implanted vagus nerve stimulation systems for epilepsy, depression, rehabilitation and inflammation",
    interfaceType: "vagus_nerve",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["vagus-nerve-stimulation", "neuromodulation"],
    conditions: [
      "epilepsy",
      "major-depressive-disorder",
      "stroke",
      "rheumatoid-arthritis",
      "obesity",
    ],
    neuralTargets: ["left cervical vagus nerve", "cervical vagus nerve"],
    intendedFunctions: [
      "vagus nerve stimulation to reduce seizure frequency",
      "rehabilitation-paired vagus nerve stimulation after stroke",
      "vagus nerve stimulation for inflammation control",
    ],
    intendedUsers:
      "adults with drug-resistant epilepsy, treatment-resistant depression or upper-limb impairment after stroke",
    deviceNouns: ["Vagal Stimulator", "VNS System", "Cervical Cuff System", "Vagus Implant"],
    limitations: [
      "Voice alteration during stimulation is common",
      "Response builds over months",
      "Battery replacement requires surgery",
    ],
    metrics: [
      {
        name: "seizure frequency reduction",
        unit: "%",
        low: 30,
        high: 65,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "upper-limb motor score change",
        unit: "points",
        low: 3,
        high: 9,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Vagus Nerve Stimulation With the {device} in {condition}",
      "Rehabilitation-Paired Vagus Nerve Stimulation With the {device} After Stroke",
      "Vagus Nerve Stimulation for Inflammation With the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Percentage reduction in seizure frequency at 12 months",
      "Upper-limb motor score change at 90 days",
      "Disease activity score at 12 weeks",
    ],
    publicationTitles: [
      "Vagus nerve stimulation with the {device} in {n} patients with {condition}",
      "Paired vagus nerve stimulation and rehabilitation after stroke: {months}-month outcomes",
      "Cervical vagus nerve stimulation reduces inflammatory markers in {condition}",
    ],
    patentTitles: [
      "Vagus nerve cuff electrode with fibre-selective stimulation",
      "Rehabilitation-triggered vagus nerve stimulator",
      "Miniaturised vagus nerve stimulator with wireless charging",
    ],
    stageWeights: {
      preclinical: 1,
      early_feasibility: 2,
      pivotal: 2,
      authorized: 2,
      commercial: 2,
    },
    keywords: [
      "vagus nerve stimulation",
      "VNS",
      "epilepsy",
      "bioelectronic medicine",
      "neuromodulation",
    ],
    forcedCompanies: 3,
    forcedDevices: 3,
  }),
  defineArchetype({
    key: "tavns",
    label: "transcutaneous auricular vagus nerve stimulator",
    productPhrase: "noninvasive transcutaneous auricular vagus nerve stimulators worn on the ear",
    interfaceType: "vagus_nerve",
    invasiveness: "noninvasive",
    modality: "stimulation",
    categories: ["vagus-nerve-stimulation", "neuromodulation"],
    conditions: ["migraine", "epilepsy", "major-depressive-disorder", "tinnitus"],
    neuralTargets: ["auricular branch of the vagus nerve", "cymba conchae"],
    intendedFunctions: [
      "noninvasive vagus nerve stimulation through the ear for migraine and seizure reduction",
    ],
    intendedUsers: "adults with migraine, epilepsy or depression seeking a noninvasive option",
    deviceNouns: ["Ear Stimulator", "Auricular VNS", "Vagal Wearable"],
    limitations: [
      "Adherence to daily sessions varies",
      "Sham-controlled evidence is limited",
      "Effect sizes are modest",
    ],
    metrics: [
      {
        name: "monthly migraine days reduction",
        unit: "days",
        low: 1.5,
        high: 5,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Transcutaneous Auricular Vagus Nerve Stimulation With the {device} for {condition}",
      "Sham-Controlled Study of the {device} in {condition}",
    ],
    primaryOutcomes: ["Change in monthly migraine days at 12 weeks", "Responder rate at 6 months"],
    publicationTitles: [
      "Transcutaneous auricular vagus nerve stimulation in {n} participants with {condition}",
      "Autonomic effects of auricular vagus nerve stimulation with the {device}",
    ],
    patentTitles: [
      "Ear-worn electrode for auricular vagus nerve stimulation",
      "Method of titrating transcutaneous vagus nerve stimulation",
    ],
    stageWeights: { research: 1, early_feasibility: 2, pivotal: 2, authorized: 1, commercial: 2 },
    keywords: [
      "transcutaneous vagus nerve stimulation",
      "auricular",
      "noninvasive neuromodulation",
      "migraine",
    ],
    forcedCompanies: 2,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "fus_neuromod",
    label: "focused ultrasound neuromodulation system",
    productPhrase:
      "low-intensity focused ultrasound systems for noninvasive deep-brain neuromodulation",
    interfaceType: "focused_ultrasound",
    invasiveness: "noninvasive",
    modality: "stimulation",
    categories: ["focused-ultrasound", "neuromodulation"],
    conditions: ["essential-tremor", "epilepsy", "major-depressive-disorder", "chronic-pain"],
    neuralTargets: ["ventral intermediate thalamus", "anterior cingulate cortex", "hippocampus"],
    intendedFunctions: [
      "transcranial focused ultrasound neuromodulation of deep targets without surgery",
      "image-guided low-intensity ultrasound stimulation",
    ],
    intendedUsers:
      "adults with tremor, epilepsy or depression who are not candidates for implanted devices",
    deviceNouns: [
      "Ultrasound Helmet",
      "Focused Ultrasound System",
      "Transcranial Array",
      "Sonic Neuromodulator",
    ],
    limitations: [
      "Requires MRI or CT-based skull correction",
      "Sessions are delivered in clinic",
      "Mechanisms of sustained effect remain under study",
    ],
    metrics: [
      {
        name: "tremor score improvement",
        unit: "%",
        low: 20,
        high: 55,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "seizure frequency reduction",
        unit: "%",
        low: 20,
        high: 55,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Low-Intensity Focused Ultrasound Neuromodulation With the {device} for {condition}",
      "Sham-Controlled Study of Transcranial Focused Ultrasound Using the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Change in tremor score at 3 months",
      "Seizure frequency at 6 months",
      "Device-related adverse events at 30 days",
    ],
    publicationTitles: [
      "Transcranial focused ultrasound neuromodulation of the thalamus in {n} participants with {condition}",
      "Safety of repeated low-intensity focused ultrasound sessions over {months} months",
      "Skull-corrected ultrasound targeting with the {device}",
    ],
    patentTitles: [
      "Phased-array transducer helmet for transcranial focused ultrasound",
      "Method for skull aberration correction in ultrasound neuromodulation",
    ],
    stageWeights: { research: 2, preclinical: 2, early_feasibility: 3, pivotal: 1 },
    keywords: [
      "focused ultrasound",
      "transcranial ultrasound",
      "noninvasive neuromodulation",
      "deep brain targets",
    ],
    forcedCompanies: 3,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "tms_neuromod",
    label: "transcranial magnetic stimulation system",
    productPhrase:
      "transcranial magnetic stimulation systems with navigated coils for psychiatric and neurological disorders",
    interfaceType: "tms",
    invasiveness: "noninvasive",
    modality: "stimulation",
    categories: ["transcranial-stimulation", "neuromodulation"],
    conditions: [
      "major-depressive-disorder",
      "obsessive-compulsive-disorder",
      "chronic-pain",
      "post-traumatic-stress-disorder",
    ],
    neuralTargets: [
      "left dorsolateral prefrontal cortex",
      "dorsomedial prefrontal cortex",
      "primary motor cortex",
    ],
    intendedFunctions: [
      "navigated transcranial magnetic stimulation for treatment-resistant depression",
      "accelerated theta-burst stimulation protocols",
    ],
    intendedUsers:
      "adults with depression or obsessive-compulsive disorder that has not responded to medication",
    deviceNouns: ["TMS System", "Navigated Coil", "Theta-Burst Platform", "Magnetic Stimulator"],
    limitations: [
      "Daily clinic visits over several weeks",
      "Coil positioning affects outcome",
      "Relapse rates after treatment courses vary",
    ],
    metrics: [
      {
        name: "depression remission rate",
        unit: "%",
        low: 25,
        high: 60,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Accelerated Theta-Burst Stimulation With the {device} for {condition}",
      "Navigated Transcranial Magnetic Stimulation Using the {device} in {condition}",
    ],
    primaryOutcomes: ["Remission rate at 4 weeks", "Change in symptom score at 6 weeks"],
    publicationTitles: [
      "Accelerated theta-burst stimulation with the {device} in {n} patients with {condition}",
      "Navigated transcranial magnetic stimulation for {condition}: a randomized trial",
    ],
    patentTitles: [
      "Actively cooled transcranial magnetic stimulation coil",
      "Neuronavigation system for coil placement",
    ],
    stageWeights: { early_feasibility: 1, pivotal: 2, authorized: 2, commercial: 3 },
    keywords: [
      "transcranial magnetic stimulation",
      "TMS",
      "theta-burst",
      "noninvasive brain stimulation",
    ],
    forcedCompanies: 3,
    forcedDevices: 2,
  }),
] as const;
