import { defineArchetype } from "./types";

export const SENSORY_REHAB_ARCHETYPES = [
  defineArchetype({
    key: "eeg_stroke_rehab",
    label: "EEG-driven stroke rehabilitation system",
    productPhrase:
      "noninvasive EEG brain-computer interfaces that decode motor imagery to drive rehabilitation robotics after stroke",
    interfaceType: "eeg",
    invasiveness: "noninvasive",
    modality: "recording",
    categories: ["noninvasive-bcis", "neurorehabilitation", "brain-computer-interfaces"],
    conditions: ["stroke", "traumatic-brain-injury"],
    neuralTargets: [
      "sensorimotor rhythms over motor cortex",
      "event-related desynchronisation in the affected hemisphere",
    ],
    intendedFunctions: [
      "EEG-based motor imagery decoding that triggers robotic or functional electrical stimulation therapy",
      "stroke rehabilitation guided by brain-computer interface feedback",
    ],
    intendedUsers: "adults with upper-limb impairment after stroke, in clinic and at home",
    deviceNouns: ["Rehab Headset", "Motor Recovery System", "EEG Trainer", "Neurofeedback Cap"],
    limitations: [
      "EEG setup time limits session length",
      "Signal quality depends on electrode contact",
      "Benefit over conventional therapy is modest in some studies",
    ],
    metrics: [
      {
        name: "upper-limb motor score change",
        unit: "points",
        low: 3,
        high: 10,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "motor imagery classification accuracy",
        unit: "%",
        low: 65,
        high: 92,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Brain-Computer Interface Guided Rehabilitation With the {device} After {condition}",
      "Home-Based EEG Neurofeedback Therapy Using the {device} in Chronic {condition}",
    ],
    primaryOutcomes: [
      "Change in upper-limb motor score at 6 weeks",
      "Adherence to home sessions over 12 weeks",
    ],
    publicationTitles: [
      "EEG brain-computer interface rehabilitation in {n} chronic stroke survivors",
      "Motor imagery decoding accuracy with a dry-electrode headset over {months} months of home use",
      "Closed-loop functional electrical stimulation driven by EEG after {condition}",
    ],
    patentTitles: [
      "Dry-electrode EEG headset for rehabilitation feedback",
      "Method for triggering functional electrical stimulation from motor imagery",
    ],
    stageWeights: { research: 1, early_feasibility: 2, pivotal: 2, authorized: 1, commercial: 2 },
    keywords: [
      "EEG",
      "stroke rehabilitation",
      "motor imagery",
      "noninvasive brain-computer interface",
      "neurorehabilitation",
    ],
    forcedCompanies: 3,
    forcedDevices: 3,
  }),
  defineArchetype({
    key: "tes_stroke_rehab",
    label: "transcranial electrical stimulation for stroke rehabilitation",
    productPhrase:
      "transcranial direct and alternating current stimulation systems paired with therapy for stroke recovery",
    interfaceType: "transcranial_electrical",
    invasiveness: "noninvasive",
    modality: "stimulation",
    categories: ["transcranial-stimulation", "neurorehabilitation", "neuromodulation"],
    conditions: ["stroke", "aphasia", "major-depressive-disorder"],
    neuralTargets: ["ipsilesional primary motor cortex", "left inferior frontal gyrus"],
    intendedFunctions: [
      "tDCS delivered alongside motor or speech therapy to enhance recovery after stroke",
      "home-use tACS with remote supervision",
    ],
    intendedUsers: "adults recovering motor or language function after stroke",
    deviceNouns: ["tDCS Headset", "Stim Cap", "Cortical Stimulator", "Current Stimulation System"],
    limitations: [
      "Individual responses vary with lesion location",
      "Skin irritation at electrode sites",
      "Optimal dosing not established",
    ],
    metrics: [
      {
        name: "upper-limb motor score change",
        unit: "points",
        low: 2,
        high: 8,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "naming accuracy improvement",
        unit: "%",
        low: 5,
        high: 25,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Transcranial Direct Current Stimulation With the {device} Paired With Therapy After {condition}",
      "Remotely Supervised Home tDCS Using the {device} for {condition}",
    ],
    primaryOutcomes: ["Change in upper-limb motor score at 4 weeks", "Naming accuracy at 8 weeks"],
    publicationTitles: [
      "Anodal tDCS with the {device} paired with therapy in {n} stroke survivors",
      "Home-based transcranial electrical stimulation for {condition}: feasibility over {months} months",
    ],
    patentTitles: [
      "Headset for consistent electrode placement in transcranial electrical stimulation",
      "Remote supervision system for home tDCS",
    ],
    stageWeights: { research: 1, early_feasibility: 2, pivotal: 2, authorized: 1, commercial: 2 },
    keywords: [
      "tDCS",
      "tACS",
      "transcranial electrical stimulation",
      "stroke rehabilitation",
      "neurorehabilitation",
    ],
    forcedCompanies: 3,
    forcedDevices: 3,
  }),
  defineArchetype({
    key: "fnirs_rehab",
    label: "fNIRS neurofeedback system for stroke rehabilitation",
    productPhrase:
      "wearable functional near-infrared spectroscopy systems for neurofeedback during stroke rehabilitation",
    interfaceType: "fnirs",
    invasiveness: "noninvasive",
    modality: "recording",
    categories: ["neuroimaging-wearables", "neurorehabilitation", "noninvasive-bcis"],
    conditions: ["stroke", "traumatic-brain-injury"],
    neuralTargets: [
      "haemodynamic responses over motor and premotor cortex",
      "prefrontal cortex oxygenation",
    ],
    intendedFunctions: [
      "fNIRS neurofeedback to reinforce motor cortex activation during rehabilitation exercises",
      "wearable brain monitoring during therapy sessions",
    ],
    intendedUsers: "adults in rehabilitation after stroke or brain injury",
    deviceNouns: [
      "fNIRS Headband",
      "Optical Rehab System",
      "Haemodynamic Monitor",
      "Near-Infrared Cap",
    ],
    limitations: [
      "Hair and skin pigmentation affect signal quality",
      "Haemodynamic responses lag neural activity by seconds",
    ],
    metrics: [
      {
        name: "upper-limb motor score change",
        unit: "points",
        low: 2,
        high: 8,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "fNIRS Neurofeedback With the {device} During Rehabilitation After {condition}",
      "Wearable fNIRS Monitoring Using the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Change in upper-limb motor score at 6 weeks",
      "Feasibility of daily sessions over 4 weeks",
    ],
    publicationTitles: [
      "fNIRS neurofeedback in {n} stroke survivors during upper-limb rehabilitation",
      "Wearable near-infrared spectroscopy over {months} months of outpatient therapy",
    ],
    patentTitles: [
      "Wearable fNIRS headband with motion-tolerant optodes",
      "Method for real-time haemodynamic neurofeedback",
    ],
    stageWeights: { research: 2, early_feasibility: 3, pivotal: 1, commercial: 1 },
    keywords: [
      "fNIRS",
      "near-infrared spectroscopy",
      "neurofeedback",
      "stroke rehabilitation",
      "wearable neuroimaging",
    ],
    forcedCompanies: 2,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "fus_rehab",
    label: "focused ultrasound neuromodulation for stroke recovery",
    productPhrase:
      "low-intensity focused ultrasound systems that modulate perilesional cortex to support motor recovery after stroke",
    interfaceType: "focused_ultrasound",
    invasiveness: "noninvasive",
    modality: "stimulation",
    categories: ["focused-ultrasound", "neurorehabilitation", "neuromodulation"],
    conditions: ["stroke", "disorders-of-consciousness"],
    neuralTargets: ["perilesional motor cortex", "central thalamus"],
    intendedFunctions: [
      "transcranial focused ultrasound to prime motor cortex before rehabilitation sessions",
      "thalamic ultrasound stimulation for disorders of consciousness",
    ],
    intendedUsers: "adults in subacute or chronic stroke rehabilitation",
    deviceNouns: ["Recovery Ultrasound", "Sonic Rehab System", "Perilesional Array"],
    limitations: [
      "Requires imaging-based targeting",
      "Delivered under clinical supervision",
      "Small early cohorts",
    ],
    metrics: [
      {
        name: "upper-limb motor score change",
        unit: "points",
        low: 2,
        high: 9,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Focused Ultrasound Priming With the {device} Before Rehabilitation After {condition}",
      "Thalamic Focused Ultrasound Using the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Change in upper-limb motor score at 8 weeks",
      "Coma recovery scale change at 4 weeks",
    ],
    publicationTitles: [
      "Focused ultrasound neuromodulation before therapy in {n} stroke survivors",
      "Thalamic low-intensity ultrasound in {condition}: a case series",
    ],
    patentTitles: [
      "Portable focused ultrasound headset for rehabilitation",
      "Method for perilesional ultrasound targeting",
    ],
    stageWeights: { research: 2, preclinical: 1, early_feasibility: 3, pivotal: 1 },
    keywords: [
      "focused ultrasound",
      "stroke rehabilitation",
      "noninvasive neuromodulation",
      "neurorehabilitation",
    ],
    forcedCompanies: 2,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "retinal",
    label: "retinal prosthesis",
    productPhrase:
      "retinal prostheses that restore light perception in retinal degeneration through epiretinal or subretinal electrode arrays",
    interfaceType: "retinal",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["retinal-prosthetics", "sensory-prosthetics"],
    conditions: ["retinitis-pigmentosa", "age-related-macular-degeneration"],
    neuralTargets: [
      "retinal ganglion cells (epiretinal array)",
      "bipolar cells (subretinal photovoltaic array)",
    ],
    intendedFunctions: [
      "restoration of light perception and coarse form vision through retinal stimulation",
      "photovoltaic subretinal stimulation driven by a camera and projection glasses",
    ],
    intendedUsers:
      "adults with profound vision loss from retinitis pigmentosa or macular degeneration",
    deviceNouns: [
      "Retinal Array",
      "Vision Implant",
      "Photovoltaic Retinal System",
      "Epiretinal Prosthesis",
    ],
    limitations: [
      "Restored vision is low resolution",
      "Requires intact retinal ganglion cells",
      "Vitreoretinal surgery carries risks of retinal detachment",
    ],
    metrics: [
      {
        name: "letter acuity (logMAR)",
        unit: "logMAR",
        low: 1.3,
        high: 2.3,
        higherIsBetter: false,
        decimals: 2,
      },
      {
        name: "grating acuity",
        unit: "cycles/degree",
        low: 0.3,
        high: 2.5,
        higherIsBetter: true,
        decimals: 2,
      },
    ],
    trialTitles: [
      "Feasibility Study of the {device} Retinal Prosthesis in {condition}",
      "Visual Function With the {device} Subretinal Implant in {condition}",
    ],
    primaryOutcomes: [
      "Grating acuity at 12 months",
      "Letter acuity at 6 months",
      "Serious ocular adverse events through 12 months",
    ],
    publicationTitles: [
      "Restoration of light perception with the {device} in {n} participants with {condition}",
      "Photovoltaic subretinal prosthesis: {months}-month visual outcomes in {condition}",
      "Form vision with a {channels}-electrode epiretinal array in {condition}",
    ],
    patentTitles: [
      "Photovoltaic subretinal pixel array",
      "Epiretinal electrode array with flexible substrate",
      "Projection glasses for driving a photovoltaic retinal implant",
    ],
    stageWeights: {
      early_feasibility: 4,
      pivotal: 2,
      regulatory_review: 1,
      authorized: 1,
      commercial: 1,
    },
    minDeviceStage: "early_feasibility",
    keywords: [
      "retinal prosthesis",
      "retinal implant",
      "vision restoration",
      "retinitis pigmentosa",
      "sensory prosthetics",
    ],
    forcedCompanies: 5,
    forcedDevices: 5,
  }),
  defineArchetype({
    key: "cochlear",
    label: "cochlear implant",
    productPhrase:
      "cochlear implant systems with thin electrode arrays and sound processors for severe hearing loss",
    interfaceType: "cochlear",
    invasiveness: "invasive",
    modality: "stimulation",
    categories: ["cochlear-implants", "sensory-prosthetics"],
    conditions: ["sensorineural-hearing-loss", "tinnitus"],
    neuralTargets: ["spiral ganglion neurons of the cochlea", "auditory nerve"],
    intendedFunctions: [
      "restoration of hearing through electrical stimulation of the auditory nerve",
      "hearing preservation with atraumatic electrode insertion",
    ],
    intendedUsers: "children and adults with severe-to-profound sensorineural hearing loss",
    deviceNouns: ["Cochlear System", "Auditory Implant", "Hearing Array", "Sound Processor"],
    limitations: [
      "Speech perception in noise remains difficult",
      "Residual hearing can be lost at insertion",
      "Music perception is limited",
    ],
    metrics: [
      {
        name: "sentence recognition in quiet",
        unit: "%",
        low: 55,
        high: 92,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "speech reception threshold in noise",
        unit: "dB SNR",
        low: 2,
        high: 12,
        higherIsBetter: false,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Hearing Outcomes With the {device} Cochlear Implant in {condition}",
      "Hearing Preservation With the {device} Slim Electrode Array",
    ],
    primaryOutcomes: [
      "Sentence recognition in quiet at 6 months",
      "Residual hearing preservation at 3 months",
    ],
    publicationTitles: [
      "Sentence recognition with the {device} in {n} adults with {condition}",
      "Hearing preservation with a slim lateral-wall electrode array over {months} months",
      "Auditory nerve responses to a {channels}-contact intracochlear array",
    ],
    patentTitles: [
      "Slim lateral-wall cochlear electrode array",
      "Sound processor with beamforming for cochlear implants",
      "Totally implantable cochlear implant microphone",
    ],
    stageWeights: { preclinical: 1, pivotal: 2, authorized: 2, commercial: 4 },
    keywords: ["cochlear implant", "hearing restoration", "auditory nerve", "sensory prosthetics"],
    forcedCompanies: 4,
    forcedDevices: 3,
  }),
  defineArchetype({
    key: "limb_prosthesis",
    label: "neuroprosthetic limb with peripheral nerve interface",
    productPhrase:
      "neuroprosthetic limbs controlled through peripheral nerve interfaces that also deliver sensory feedback",
    interfaceType: "peripheral_nerve",
    invasiveness: "invasive",
    modality: "both",
    categories: ["neuroprosthetic-limbs", "peripheral-nerve-stimulation", "sensory-prosthetics"],
    conditions: ["limb-loss", "phantom-limb-pain"],
    neuralTargets: [
      "median and ulnar nerve fascicles",
      "regenerative peripheral nerve interfaces",
      "residual limb nerves",
    ],
    intendedFunctions: [
      "intuitive control of a prosthetic hand from peripheral nerve recordings",
      "sensory feedback restored through peripheral nerve stimulation",
    ],
    intendedUsers: "adults with upper-limb amputation",
    deviceNouns: [
      "Nerve Interface Hand",
      "Bionic Limb System",
      "Fascicular Interface",
      "Sensory Prosthesis",
    ],
    limitations: [
      "Requires surgery to place nerve interfaces",
      "Prosthesis weight and socket fit affect daily use",
      "Sensory percepts are limited in naturalness",
    ],
    metrics: [
      {
        name: "grasp classification accuracy",
        unit: "%",
        low: 80,
        high: 97,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "phantom limb pain reduction",
        unit: "%",
        low: 25,
        high: 70,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Bidirectional Peripheral Nerve Interface With the {device} in {condition}",
      "Sensory Feedback Through Peripheral Nerve Stimulation Using the {device}",
    ],
    primaryOutcomes: [
      "Grasp classification accuracy at 6 months",
      "Change in phantom limb pain at 12 months",
    ],
    publicationTitles: [
      "Bidirectional prosthetic hand control through peripheral nerve interfaces in {n} participants with {condition}",
      "Sensory feedback from intraneural stimulation over {months} months of home use",
      "Regenerative peripheral nerve interfaces for prosthesis control",
    ],
    patentTitles: [
      "Intrafascicular electrode with sensory stimulation channels",
      "Regenerative peripheral nerve interface construct",
      "Prosthetic hand controller with nerve-derived intent decoding",
    ],
    stageWeights: { research: 1, preclinical: 1, early_feasibility: 4, pivotal: 1, commercial: 1 },
    keywords: [
      "neuroprosthetic limb",
      "peripheral nerve interface",
      "sensory feedback",
      "prosthesis control",
    ],
    forcedCompanies: 3,
    forcedDevices: 3,
  }),
  defineArchetype({
    key: "epilepsy_monitoring",
    label: "implanted seizure monitoring and responsive neurostimulation system",
    productPhrase:
      "implanted systems that record cortical activity continuously to detect seizures and deliver responsive neurostimulation",
    interfaceType: "ecog",
    invasiveness: "invasive",
    modality: "both",
    categories: [
      "epilepsy-monitoring",
      "responsive-neurostimulation",
      "closed-loop-systems",
      "neural-recording-hardware",
    ],
    conditions: ["epilepsy"],
    neuralTargets: ["seizure onset zone (subdural strips)", "hippocampus (depth electrodes)"],
    intendedFunctions: [
      "long-term epilepsy monitoring with seizure detection and forecasting",
      "responsive neurostimulation triggered at seizure onset",
    ],
    intendedUsers: "adults with drug-resistant focal epilepsy",
    deviceNouns: [
      "Seizure Monitor",
      "Responsive Stimulator",
      "Cortical Monitor",
      "Epilepsy System",
    ],
    limitations: [
      "Requires accurate localisation of the seizure onset zone",
      "Benefit accrues gradually over years",
      "Detection thresholds need individual tuning",
    ],
    metrics: [
      {
        name: "seizure frequency reduction",
        unit: "%",
        low: 40,
        high: 78,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "seizure detection sensitivity",
        unit: "%",
        low: 85,
        high: 99,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Responsive Neurostimulation With the {device} in {condition}",
      "Long-Term Cortical Monitoring Using the {device} for Seizure Forecasting",
    ],
    primaryOutcomes: [
      "Percentage reduction in seizure frequency at 12 months",
      "Seizure detection sensitivity against video-EEG",
    ],
    publicationTitles: [
      "Responsive neurostimulation with the {device} in {n} patients with {condition}",
      "Seizure forecasting from chronic intracranial recordings over {months} months",
      "Multi-year cortical recordings from an implanted epilepsy monitor",
    ],
    patentTitles: [
      "Implantable seizure detector with responsive stimulation",
      "Method for seizure forecasting from chronic intracranial EEG",
      "Subdural strip electrode with integrated telemetry",
    ],
    stageWeights: {
      preclinical: 1,
      early_feasibility: 2,
      pivotal: 2,
      authorized: 2,
      commercial: 2,
    },
    keywords: [
      "epilepsy monitoring",
      "responsive neurostimulation",
      "seizure detection",
      "intracranial EEG",
      "closed-loop",
    ],
    forcedCompanies: 4,
    forcedDevices: 4,
  }),
  defineArchetype({
    key: "epilepsy_wearable",
    label: "subscalp EEG seizure monitor",
    productPhrase:
      "minimally invasive subscalp EEG systems for continuous seizure counting and epilepsy monitoring",
    interfaceType: "eeg",
    invasiveness: "minimally_invasive",
    modality: "recording",
    categories: ["epilepsy-monitoring", "neuroimaging-wearables", "neural-recording-hardware"],
    conditions: ["epilepsy"],
    neuralTargets: ["subscalp EEG over the temporal lobe", "bilateral subscalp leads"],
    intendedFunctions: [
      "objective seizure counting over months with a subscalp implant",
      "epilepsy monitoring outside the hospital",
    ],
    intendedUsers: "adults with epilepsy whose seizure diaries are unreliable",
    deviceNouns: ["Subscalp Monitor", "Seizure Counter", "Ultra-Long EEG"],
    limitations: [
      "Fewer channels than scalp EEG",
      "Implant site discomfort in early weeks",
      "Detection algorithms need individual review",
    ],
    metrics: [
      {
        name: "seizure detection sensitivity",
        unit: "%",
        low: 80,
        high: 96,
        higherIsBetter: true,
        decimals: 1,
      },
    ],
    trialTitles: [
      "Ultra-Long-Term Subscalp EEG With the {device} in {condition}",
      "Seizure Counting Accuracy of the {device} Compared With Video-EEG",
    ],
    primaryOutcomes: [
      "Seizure detection sensitivity against video-EEG",
      "Device-related adverse events at 6 months",
    ],
    publicationTitles: [
      "Subscalp EEG seizure monitoring in {n} patients with {condition} over {months} months",
      "Circadian and multiday seizure cycles from ultra-long-term EEG",
    ],
    patentTitles: [
      "Subscalp electrode lead with minimal-incision insertion tool",
      "Method for seizure counting from subscalp EEG",
    ],
    stageWeights: { early_feasibility: 2, pivotal: 2, authorized: 1, commercial: 1 },
    keywords: [
      "subscalp EEG",
      "seizure monitoring",
      "epilepsy monitoring",
      "wearable neurophysiology",
    ],
    forcedCompanies: 2,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "optogenetics",
    label: "optogenetic neural interface",
    productPhrase:
      "optogenetic neural interfaces combining gene delivery with implantable light sources for cell-type-specific control",
    interfaceType: "optogenetic",
    invasiveness: "invasive",
    modality: "both",
    categories: ["optogenetics", "neural-recording-hardware"],
    conditions: ["epilepsy", "chronic-pain", "retinitis-pigmentosa"],
    neuralTargets: [
      "opsin-expressing cortical interneurons",
      "dorsal root ganglion nociceptors",
      "retinal ganglion cells expressing channelrhodopsin",
    ],
    intendedFunctions: [
      "optogenetic silencing of seizure circuits",
      "optogenetic vision restoration with a light-stimulating goggle",
      "cell-type-specific pain modulation",
    ],
    intendedUsers:
      "research programmes and early clinical studies in epilepsy, pain and retinal degeneration",
    deviceNouns: ["Optrode Array", "Photonic Implant", "Light Delivery System", "Opsin Interface"],
    limitations: [
      "Requires viral gene delivery",
      "Light penetration limits target depth",
      "Long-term opsin expression stability is uncertain in humans",
    ],
    metrics: [
      {
        name: "seizure suppression rate",
        unit: "%",
        low: 40,
        high: 85,
        higherIsBetter: true,
        decimals: 1,
      },
      {
        name: "light-evoked response threshold",
        unit: "mW/mm^2",
        low: 0.5,
        high: 5,
        higherIsBetter: false,
        decimals: 2,
      },
    ],
    trialTitles: [
      "Optogenetic Vision Restoration With the {device} in {condition}",
      "Feasibility of Optogenetic Neuromodulation Using the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Light-evoked visual perception at 6 months",
      "Adverse events through 12 months",
    ],
    publicationTitles: [
      "Optogenetic silencing of seizures with the {device} in a rodent model",
      "Partial vision restoration after optogenetic therapy in a participant with {condition}",
      "A {channels}-site optrode array for combined recording and light delivery",
    ],
    patentTitles: [
      "Optrode array with integrated micro-LEDs",
      "Wearable light stimulation goggles for optogenetic vision restoration",
      "Method for cell-type-specific neuromodulation using engineered opsins",
    ],
    stageWeights: { research: 4, preclinical: 4, early_feasibility: 1 },
    keywords: ["optogenetics", "opsin", "light stimulation", "gene therapy", "optrode"],
    forcedCompanies: 3,
    forcedDevices: 2,
  }),
  defineArchetype({
    key: "wearable_meg",
    label: "wearable magnetoencephalography system",
    productPhrase:
      "wearable optically pumped magnetometer MEG systems for clinical neuroimaging outside shielded rooms",
    interfaceType: "meg",
    invasiveness: "noninvasive",
    modality: "recording",
    categories: ["neuroimaging-wearables", "neural-recording-hardware"],
    conditions: ["epilepsy", "alzheimer-disease", "traumatic-brain-injury"],
    neuralTargets: ["whole-cortex magnetic fields", "temporal lobe interictal activity"],
    intendedFunctions: [
      "wearable MEG for interictal spike localisation in epilepsy",
      "naturalistic neuroimaging of cognition in movement",
    ],
    intendedUsers: "epilepsy centres and cognitive neuroscience laboratories",
    deviceNouns: ["OPM Helmet", "Wearable MEG", "Magnetometer Array"],
    limitations: [
      "Requires a magnetically shielded environment",
      "Sensor count is lower than cryogenic MEG",
      "Movement range remains limited",
    ],
    metrics: [
      {
        name: "sensor channels",
        unit: "channels",
        low: 64,
        high: 320,
        higherIsBetter: true,
        decimals: 0,
      },
    ],
    trialTitles: [
      "Wearable MEG With the {device} for Interictal Spike Localisation in {condition}",
      "Naturalistic Neuroimaging Using the {device} in {condition}",
    ],
    primaryOutcomes: [
      "Concordance of spike localisation with cryogenic MEG",
      "Usable recording time per session",
    ],
    publicationTitles: [
      "Wearable optically pumped magnetometer MEG in {n} patients with {condition}",
      "Whole-head wearable MEG during natural movement",
    ],
    patentTitles: [
      "Optically pumped magnetometer helmet with adjustable sensor mounts",
      "Method for background field nulling in wearable MEG",
    ],
    stageWeights: { research: 3, preclinical: 1, early_feasibility: 2, commercial: 1 },
    keywords: [
      "magnetoencephalography",
      "MEG",
      "optically pumped magnetometers",
      "wearable neuroimaging",
    ],
    forcedCompanies: 2,
    forcedDevices: 2,
  }),
] as const;
